### ISSUE TITLE
Compare mapfiles to ensure integrity

### ISSUE THREAD

**Issue by ffledgling** [ffledgling/vcs2aws#12]
- [ ] Compare Legacy Production and AWS
- [ ] Compare Modern Production and AWS
  - [x] l10n
  - [ ] Project branches
  - [ ] beagle
- [ ] Compare AWS Modern and AWS Legacy (will probably only for l10n for now).

**Comment by ffledgling** [comment]
Progress update: Attempted to cross check l10n on modern AWS and legacy AWS, mapfiles don't seem to match in terms of structure/layout. I looked at the ones in `$MODERN_HOME/build/uploads/` and `$REPO_PATH/.hg/git-mapfile` for files in legacy. I specifically searched for l10n gaia for de by hand, there seem to be mapfiles per branch on modern, and just one mapfile per-repo for legacy.

The mapfiles in modern appear to be subsets of:
1. One another (v1_2 is subset of v2_1 which is subset of head), which makes sense.
2. head from modern (and thus all branches mapfiles as well), appear to be subsets of the mapfiles in legacy. Not entirely sure why, will need more info on this.

**Comment by hwine** [comment]
Legacy "batches" all locales into a single mapfile. That implies the CI code accessing the l10n maps does not specify the locale in the query. For modern, that would require that all PUT to mapper be to a single "project" to consume 
See [legacy mapper](http://people.mozilla.org/~hwine/tmp/vcs2vcs/mapper_support.html) and [combine_mapfiles](http://hg.mozilla.org/users/hwine_mozilla.com/repo-sync-tools/raw-file/default/combine_mapfiles) for details.

What I think the mapfile location you observed is that modern does the hg-git conversion on the individual clones of upstream repos, and then locally pushes the result to the combined target repo, which is then pushed to the remote.

**Comment by ffledgling** [comment]
I found 'grouped' l10n mapfiles in both modern and legacy.

Modern: ` /home/vcs2vcs/vcs_sync/build/upload/l10n-mapfile`
Legacy: ` /tmp/vcs-sync/l10n-mapfile`

There's still *extremely* large differences in the number of commits listed/mapped in both files.

To view the differences, you can do the following:

```
vimdiff <(ssh -t ec2-user@52.11.210.32 sudo cat /tmp/vcs-sync/l10n-mapfile) <(ssh -t ec2-user@52.24.123.175 sudo cat /home/vcs2vcs/vcs_sync/build/upload/l10n-mapfile)
```

You might have to wait for it to buffer a little.

**Comment by ffledgling** [comment]
I found 'grouped' l10n mapfiles in both modern and legacy.

Modern: `/home/vcs2vcs/vcs_sync/build/upload/l10n-mapfile`
Legacy: `/tmp/vcs-sync/l10n-mapfile`

There's still _extremely_ large differences in the number of commits listed/mapped in both files.

Legacy has all the commits from the modern mapfile, but they're few and far between.

To view the differences, you can do the following:

```
vimdiff <(ssh -t ec2-user@$LEGACY_IP sudo cat /tmp/vcs-sync/l10n-mapfile) <(ssh -t ec2-user@$MODERN_IP sudo cat /home/vcs2vcs/vcs_sync/build/upload/l10n-mapfile)
```

You might have to wait for it to buffer a little.

**Comment by ffledgling** [comment]
Based on discussion with @hwine, modern and legacy don't work on _exactly_ the same inputs and don't have the _exact_ same outputs, therefore, at the moment, mapfiles are not a good proxy.

Using check-modern-l10n to compare production modern and modern on AWS as proxy, which checks the git conversions' master's HEAD for l10n and checks to see if they match. Marking this bit as done.
