### ISSUE TITLE
Missing mail command

### ISSUE THREAD

**Issue by ffledgling** [ffledgling/vcs2aws#22]
Cron error with the following message on the vcs-sync-legacy box:

```
/home/vcs2vcs/bin/check_process_delay: line 45: mail: command not found
```

**Comment by hwine** [comment]
fixed with update to do_update script to use 'sendmail' if 'mail' is not available. See http://hg.mozilla.org/users/hwine_mozilla.com/repo-sync-tools/rev/16cca2ab7a68
