### ISSUE TITLE
Consider moving away from manually installed items in ~vcs2vcs for modern to installing them via yum

### ISSUE THREAD

**Issue by ffledgling** [ffledgling/vcs2aws#5]
Examples of note:
- python27-lockfile, required by run_l10n_sync.sh

**Comment by hwine** [comment]
`lockfile` is not a python package. Comes as part of procmail:

```
[ec2-user@ip-172-31-30-125 ~]$ type -a lockfile
lockfile is /usr/bin/lockfile
[ec2-user@ip-172-31-30-125 ~]$ rpm -qf /usr/bin/lockfile 
procmail-3.22-25.1.6.amzn1.x86_64
```

**Comment by ffledgling** [comment]
There doesn't seem to be anything on modern that needs to be installed via pip/via other means at all. Legacy does, but I'm assuming that's because the version of Python and hg are pinned. If that's correct, then I'll document/make changes in playbooks accordingly and close out this issue. @hwine 
comments?

**Comment by hwine** [comment]
Sorry I missed this - still sorting out what is, and is not, needed. I believe we now have no dependencies on ~vcs2vcs/bin.
Modern does need hg installed, but system wide is fine.

**Comment by ffledgling** [comment]
System-wide hg is covered by the playbook here -- https://github.com/ffledgling/vcs2aws/blob/master/modern_software.playbook.yml#L20 (we always install the latest, since I didn't quite see any version requirements anywhere). I think nothing else depends on ~vcs2vcs/bin as well, just the lockfile, which is pre-installed on Amazon AMIs.
