### ISSUE TITLE
Free up AWS snapshots from releng

### ISSUE THREAD

**Issue by hwine** [ffledgling/vcs2aws#7]
Task - after vcssync1 & vcssync2 are shut down:
- [ ] unmount from dev services hosts
- [ ] detach from dev services instances
- [ ] ask releng to delete in AWS

**Comment by ffledgling** [comment]
Is there a reason why dev-services can't keep a copy of the snapshot while releng deletes it from their AWS?

**Comment by hwine** [comment]
Why do that extra work? We'd have to make a copy in our account, then remount, then tell releng to release. In the meantime it serves double duty as a backup for production (still in releng)
